name: 'Dad Joke Action'
description: 'Get a random dad joke'

# Aquí defines lo que tu acción devuelve (outputs)
outputs:
  joke:
    description: 'The random dad joke string'

# Aquí es donde le dices a GitHub qué archivo ejecutar
runs:
  using: 'node20'
  main: 'dist/index.js'
